### ISSUE TITLE
Table styles

### ISSUE THREAD

**Issue by teenwolfblitzer** [Kajabi/sage-archived#184]
Revise table styles for use in admin & superadmin
- [x] Table header sort indicators - current sort visibility, sortable column link appearance (#244)
- [x] Column spacing and alignment (#186)
- [x] Show/hide columns (#252)
- [ ] ~Embedded button styles - TBD~
- [ ] Filtering and search — FUTURE (final implementation TBD)

**Comment by teenwolfblitzer** [comment]
Primary tasks are complete. Closing this one out in favor of #255 for extended work.
