### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by teenwolfblitzer** [Kajabi/sage-archived#24]
Update typography section of Sage documentation:
- [x] Update font loading (#25)
- [x] Add specs to indicate individual font sizes, weights, line-heights, kerning, and optimal line lengths (#28)
- [x] Favor specifying relative units `rem` over `px` on font-sizing (https://www.24a11y.com/2019/pixels-vs-relative-units-in-css-why-its-still-a-big-deal/) (#28)
- [x] Extend examples to include paragraphs, lists, and other items (#29)
